---
- name: Add Web Upd8 Oracle Java PPA
  become: yes
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present

- name: Install Oracle Java 8 Runtime
  become: yes
  apt:
    name: openjdk-8-jre
    update_cache: yes
    state: present

- name: Configure the Jenkins APT key
  apt_key: url=http://pkg.jenkins.io/debian/jenkins.io.key
           state=present

- name: Configure the Jenkins APT repositories
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/"
                  state=present

- name: Install Jenkins
  apt:
    pkg: jenkins
    state: present

#- name: Set user-defined configuration options
#  template: src=jenkins.j2
#            dest=/etc/default/jenkins

- name: Remove Jenkins password
  lineinfile:
    path: /var/lib/jenkins/config.xml
    regexp: '<useSecurity>true</useSecurity>'
    line: '<useSecurity>false</useSecurity>'
    state: present

# Testing plug installation to avoid any manual change on Jenkins
#- name: Install Jenkins plugin
#  jenkins_plugin:
#    name: "{{ item }}"
#    with_items:
#      -
- name: Add user jenkins to docker group
    - shell: sudo usermod -a -G docker jenkins

  notify:
    - Restart Jenkins